### ISSUE TITLE
Unable to set the colour of the done button when showing the Smooch view controller in a tab bar

### ISSUE THREAD

**Issue by MalcolmScoffable** [zendesk/sunshine-conversations-ios#210]
I'm currently integrating this SDK into my app, and all is working well. However, one annoying issue I've got is that the "Done" button shown as the right hand navigation item when showing the view controller in a tab controller is always black, despite the rest of the navbar having different tint colors (white). Is there anyway of updating the style for this? I've not been able to find any solutions in the documentation or by scouring other issues.

I may be missing something, and this may be relatively minor. However it does mean that the SDK doesn't quite integrate properly with the app, and makes the UI for the chat view look a bit out of place.

**Comment by MalcolmScoffable** [comment]
OK, so I managed to sort of resolve this by hacking the navigation bar style to black as follows:
```navigationController?.navigationBar.barStyle = .black```

This is fine for what I'm trying to do as I just wanted the done button to be white. However it does seem a bit inflexible that the colour of this button can't be changed to match the general tint of the navigation bar. Maybe something to fix in a future release?

**Comment by DataWearsAHood** [comment]
@MalcolmScoffable Are you able to post screenshots of the default behaviour and what you were able/trying to achieve?
Please also confirm the following details from the Issue template:

 **What is the current behavior?**

> the "Done" button shown as the right hand navigation item when showing the view controller in a tab controller is always black, despite the rest of the navbar having different tint colors (white)

 **Please provide the steps to reproduce and, if possible, a minimal demo of the problem**. Ideally a sample project

 **What is the expected behavior?**

> anyway of updating the style for this? [...] I just wanted the done button to be white.

 **Please tell us about your environment:**
- SDK version
- OS version
 
**Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. Stack Overflow, etc)
